import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Provider from "./client-provider";
import Navbar from "./navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Git Scanner",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
    <body>
      {/* {session ? <Navbar /> : ""} */}
      {/* <Navbar/> */}
      <div className="main-content">
      <Provider session={session}>
        <Navbar/>
      <div>
      {children}
      </div>
      </Provider>
      </div>
    </body>
  </html>
  );
}
